config/routes.rb
WgoHungRor::Application.routes.draw do
  
  match 'users/saveUser' => 'users#saveUser', :as => :saveUser  
  match 'users/editUser' => 'users#editUser', :as => :editUser
  match 'users/destroy/:id' => 'users#destroy', :as => :destroy
  match 'users/authenticate' => 'users#authenticate', :as => :authenticate
  match 'users/insertUser' => 'users#insertUser', :as => :insertUser
  match 'users/:id/update' => 'users#update', :as => :update
  match 'festivals/destroy/:id' => 'festivals#destroy', :as => :destroy
  
  resources :users

  resources :festivals

  root :to => 'users#index'

end

app/models/festival.rb
class Festival < ActiveRecord::Base
end

app/controllers/festivals_controller.rb
class FestivalsController < ApplicationController

  # GET /festivals
  # GET /festivals.json
  # http://wgo-hung-ror.herokuapp.com/users/insertUser//changed to blooming something heroku
  def index
    # @offset, @limit = api_offset_and_limit
    @festivals =  Festival.find :all
                        # :limit  =>  @limit,
                        # :offset =>  @offset
    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => {:Success => true, :Data => @festivals}, :callback => params[:callback] }
    end
  end

  # GET /festivals/1
  # GET /festivals/1.json
  def show
    @festival = Festival.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @festival }
    end
  end

  # GET /festivals/new
  # GET /festivals/new.json
  def new
    @festival = Festival.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @festival }
    end
  end

  # GET /festivals/1/edit
  def edit
    @festival = Festival.find(params[:id])
  end

  # POST /festivals
  # POST /festivals.json
  def create    
    puts request.params[:festival]["id"] #[:id].to_i
    puts params[:festival]
    puts '************************************************************'
    if request.params[:festival]["id"]
      puts 'Into the if loop'
      params[:festival] = JSON.parse(params[:festival])
      puts params[:festival]
    end
    puts '************************************************************'
    puts params[:festival]
    #@festival = Festival.new(:name =>params[:festival][:name], :details => params[:festival][:details],:city=> params[:festival][:city],:period=> params[:festival][:period],:timings=> params[:festival][:timings], :telephone => params[:festival][:telephone])    
    @festival = Festival.new(params[:festival])
    respond_to do |format|
      if @festival.save
        format.html { redirect_to @festival, notice: 'Festival was successfully created.' }
        format.json { render json: @festival, status: :created, location: @festival }
      else
        format.html { render action: "new" }
        format.json { render json: @festival.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /festivals/1
  # PUT /festivals/1.json
  def update
    @festival = Festival.find(params[:id])
    if(@festival.update_attributes(:name => params[:name], :details => params[:details], :city => params[:city], :period => params[:period], :timings => params[:timings], :telephone => params[:telephone]))
      respond_to do |format|
         format.html { redirect_to @festival, notice: 'Festival was successfully updated.' }
         format.json { render :json => {:Success => true}, :callback => params[:callback] }
      end
    else
      respond_to do |format|
         format.html { render action: "edit" }
         format.json { render :json => {:Success => true}, :callback => params[:callback] }
      end
    end
  end

  # DELETE /festivals/1
  # DELETE /festivals/1.json
  # http://localhost:3000/festivals/destroy/1
  # http://wgo-hung-ror.herokuapp.com/festivals/destroy/1
  # This URL is used to delete or destroy a particular festival
  def destroy
    @festival = Festival.find(params[:id])
    @festival.destroy

    respond_to do |format|
      format.html { redirect_to festivals_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/festivals_helper.rb
module FestivalsHelper
end

app/views/festivals/_form.html.erb
<%= form_for(@festival) do |f| %>
  <% if @festival.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@festival.errors.count, "error") %> prohibited this festival from being saved:</h2>

      <ul>
      <% @festival.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :details %><br />
    <%= f.text_field :details %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :period %><br />
    <%= f.text_field :period %>
  </div>
  <div class="field">
    <%= f.label :timings %><br />
    <%= f.text_field :timings %>
  </div>
  <div class="field">
    <%= f.label :telephone %><br />
    <%= f.text_field :telephone %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/festivals/edit.html.erb
<h1>Editing festival</h1>

<%= render 'form' %>

<%= link_to 'Show', @festival %> |
<%= link_to 'Back', festivals_path %>

app/views/festivals/index.html.erb
<h1>Listing festivals</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Details</th>
    <th>City</th>
    <th>Period</th>
    <th>Timings</th>
    <th>Telephone</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @festivals.each do |festival| %>
  <tr>
    <td><%= festival.name %></td>
    <td><%= festival.details %></td>
    <td><%= festival.city %></td>
    <td><%= festival.period %></td>
    <td><%= festival.timings %></td>
    <td><%= festival.telephone %></td>
    <td><%= link_to 'Show', festival %></td>
    <td><%= link_to 'Edit', edit_festival_path(festival) %></td>
    <td><%= link_to 'Destroy', festival, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Festival', new_festival_path %>

app/views/festivals/new.html.erb
<h1>New festival</h1>

<%= render 'form' %>

<%= link_to 'Back', festivals_path %>

app/views/festivals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @festival.name %>
</p>

<p>
  <b>Details:</b>
  <%= @festival.details %>
</p>

<p>
  <b>City:</b>
  <%= @festival.city %>
</p>

<p>
  <b>Period:</b>
  <%= @festival.period %>
</p>

<p>
  <b>Timings:</b>
  <%= @festival.timings %>
</p>

<p>
  <b>Telephone:</b>
  <%= @festival.telephone %>
</p>


<%= link_to 'Edit', edit_festival_path(@festival) %> |
<%= link_to 'Back', festivals_path %>